### PR TITLE
Add load from optional file

### PR DESCRIPTION
**Pull request by nikbucher**

### CODE REVIEW

**Comment by nikbucher** [comment]
I think this solves the issue #18.

**Comment by ColinHebert** [comment]
This PR sounds awesome! When can we get it merged?

**Comment by wguttmn** [comment]
Until this gets merged and released, simply add the following extension to your own code and you are fine.
```
package tools.extensions

import com.natpryce.konfig.ConfigurationProperties
import com.natpryce.konfig.EmptyConfiguration
import java.io.File

/**
 * Load from optional file
 */
fun ConfigurationProperties.Companion.fromOptionalFile(file: File) = if (file.exists()) fromFile(file) else EmptyConfiguration
```

**Comment by nikbucher** [comment]
Thank you very much!

**Pull request merged**
